### ISSUE TITLE
Received event from pull_request, but also received a before or after

### ISSUE THREAD

**Issue by ThiefMaster** [trilom/file-changes-action#97]
I'm getting this warning:

```
Run trilom/file-changes-action@v1.2.3
##[warning]Received event from pull_request, but also received a before(f35bae5ca5b40913c37cbf26692edcca97bdab5b) or after(8899fae77545c573fdf69edac81b8c14258c010f) value.
I am assuming you want to use a Push event but forgot something, so I'm giving you a message.
```

This is just a normal run for a pull request I just updated (tried both with normal and forcee push). The before/after are old/new head of the PR's branch.

I do not care about individual commit. All I want is the list of files changed in the PR (ie between the base branch and the new head). Is this possible with this action? Or am I misunderstanding how it works?

**Comment by ravikp7** [comment]
This action was working fine for me since last 2 weeks to get the file changes on pull_request. Suddenly, today I'm now seeing this error and my workflow is broken. I'm not sure what's the issue, any help would be highly appreciated.

**Comment by trilom** [comment]
This should be resolved in #99

**Comment by mrchief** [comment]
Is this released yet? I'm on 1.2.4 and still see this warning.

**Comment by electriquo** [comment]
> Is this released yet? I'm on 1.2.4 and still see this warning.

It has been a long time since the question was asked and the issue still persists.
Is this project been abandoned?

@trilom on your spare time, could you kindly double check?
